spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/country
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: classpath:db/master.xml
