spring:
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/country
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: classpath:db/master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

country:
  jwt:
    duration: 1
    chrono: hours